name: Download monthly fz8 file

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Repo auschecken
      uses: actions/checkout@v3

    - name: Python einrichten
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Abh√§ngigkeiten installieren
      run: pip install requests

    - name: Datei herunterladen
      run: python download_multiple_files_at_once.py

    - name: Dateien ins Repo committen
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add downloads/ combined_data.csv
        git commit -m "Monatliches Update der XLSX-Datei"
        git push
      continue-on-error: true
